### ISSUE TITLE
Bug: SupAdmin foi pausado em Pausar_CNPJ, mas não consigo despausar 

### ISSUE THREAD

**Issue by marcioonodera** [bndes/rbb-identificacao#19]
Queria testar a pausa do SupAdmin, Não consegui usar a função "Pausar/Reativar", deu Erro ao pausar conta blockchain.

Erro 1: Mensagem de erro, mesmo com a transação aceita. Pausei o SupAdmin na função Pausar_CNPJ. Nesse caso, abriu o Metamask, aprovei e, apesar de ter recebido erro "Erro ao pausar blockchain", sistema atualizou para Lista e mostrou que a conta SupAdmin havia sido pausada.

Erro 2: Agora não consigo Despausar a conta SupAdmin, nem pelo "Pausar/Reativar", nem pelo "Pausar_CNPJ". 

![image](https://user-images.githubusercontent.com/42449573/110523849-6bdc3780-80f1-11eb-8afc-f91cc2bb043b.png)

**Comment by brunolima97** [comment]
Aguardando testes da nova versao do codigo.
