### ISSUE TITLE
Bug: Gerenciar contas: Back busca arquivo indevidamente -(Retestar em DSV, deve ser ligado a ambiente)

### ISSUE THREAD

**Issue by marcioonodera** [bndes/rbb-identificacao#24]
Para montar o painel de gerenciamento, o back está buscando arquivo de declaração para conta regular, o que existe somente para conta Admin.

![image](https://user-images.githubusercontent.com/42449573/112888209-73687e00-90aa-11eb-8dde-faa55aa04a69.png)

**Comment by brunolima97** [comment]
Aguardando dsv
